const Discord = require("discord.js")
const db = require('quick.db')

module.exports.run = async (client, message, args) => {
    db.add(`normalpoints_${message.guild.id}_${message.author.id}`, 1)
    const embed = new Discord.MessageEmbed()
    .setColor('GOLD')
    .setTitle("Luxio | The No Mercy Moderator")
    .addField("ban", 'lxban <user> [reason]', true)
    .addField("tempban", 'lxytempban <user> <time> [reason]', true)
    .addField("unban", 'lxunban <id>', true)
    .addField("banlist", `lxbanlist`, true)
    .addField("createch", 'lxcreatech <name>', true)
    .addField("createrole", 'lxcreaterole <name>', true)
    .addField("deletech", 'lxdeletech <channel>', true)
    .addField("kick", 'lxkick <user>', true)
    .addField("addrole", 'lxaddrole <user> <role>', true)
    .addField("announce", `lxannounce <channel> <text>`, true)
    .addField("delrole", 'lxdelrole <user> <role>', true)
    .addField("dm", 'lxdm <user> <text>', true)
    .addField("lock", 'lxlock', true)
    .addField("lockdown", 'lxlockdown ', true)
    .addField("mute", 'lxmute <user> [reason]', true)
    .addField("unmute", 'lxunmute <user>', true)
    .addField("tempmute", 'lxtempmute <user> <time> [reason]', true)
    .addField("purge", 'lxpurge <amount>', true)
    .addField("purgeuser", `lxpurgeuser <user>`, true)
    .addField("setnick", `lxsetnick <user> <name>`, true)
    .addField("resetnick", `lxresetnick <user>`, true)
    .addField("slowmode", `lxslowmode <time>`, true)
    .addField("warn", 'lxwarn <user> <reason>', true)
    .addField("warning", `lxwarning <user>`, true)
    .addField("resetwarn", `lxresetwarn <user>`, true)
    .setFooter('<> = Required | [] = Optional | Time = 5s (seconds)/ 5m (minutes)/ 5h (hours)')
    .setTimestamp()
    message.channel.send(embed)
}