const Discord = require("discord.js")
const db = require('quick.db')

module.exports.run = async (client, message, args) => {
    db.add(`normalpoints_${message.guild.id}_${message.author.id}`, 1)
    const embed = new Discord.MessageEmbed()
    .setColor('GOLD')
    .setTitle("Luxio | The No Mercy Moderator")
    .addField("help", 'lxhelp', true)
    .addField("helpmoderation", 'lxhelpmod', true)
    .addField("helpinfo", `lxhelpinfo`, true)
    .addField("quickhelp", 'lxquickhelp', true)
    .addField("invite", 'lxinvite', true)
    .addField("botinfo", `lxbotinfo`, true)
    .addField("userinfo", 'lxuserinfo <user>', true)
    .addField("serverinfo", 'lxserverinfo', true)
    .addField("roleinfo", 'lxroleinfo <role>', true)
    .addField("channelinfo", 'lxchannelinfo [channel]', true)
    .addField("points", 'lxpoints [user]', true)
    .addField("banlist", 'lxbanlist', true)
    .addField("ping", 'lxping', true)
    .addField("problem", 'lxproblem', true)
    .addField("bugreport", 'lxbugreport <text>', true)
      .setTimestamp()
    .setFooter("<> = required | [] = optional")
    message.channel.send(embed)
}