const Discord = require("discord.js")
const db = require('quick.db')

module.exports.run = async (client, message, args) => {
    db.add(`normalpoints_${message.guild.id}_${message.author.id}`, 1)
    const embed = new Discord.MessageEmbed()
    .setColor('GOLD')
    .setThumbnail("https://cdn.discordapp.com/attachments/905974080975544462/928517626613882931/discord-avatar-128-EZ57O.gif")
    .setTitle("Luxio | The No Mercy Moderator")
    .addField("help", 'lxhelp', true)
    .addField("helpmoderation", 'lxhelpmod', true)
    .addField("helpinfo", `lxhelpinfo`, true)
    .addField("quickhelp", 'lxquickhelp', true)
    .addField("invite", 'lxinvite', true)
    .addField("botinfo", `lxbotinfo`, true)
    .addField("userinfo", 'lxuserinfo <user>', true)
    .addField("serverinfo", 'lxserverinfo', true)
    .addField("roleinfo", 'lxroleinfo <role>', true)
    .addField("channelinfo", 'lxchannelinfo [channel]', true)
    .addField("banlist", 'lxbanlist', true)
    .addField("ping", 'lxping', true)
    .addField("problem", 'lxproblem', true)
    .addField("ban", 'lxban <user> [reason]', true)
    .addField("tempban", 'lxytempban <user> <time> [reason]', true)
    .addField("unban", 'lxunban <id>', true)
    .addField("banlist", `lxbanlist`, true)
    .addField("createch", 'lxcreatech <name>', true)
    .addField("createrole", 'lxcreaterole <name>', true)
    .addField("deletech", 'lxdeletech <channel>', true)
    .addField("kick", 'lxkick <user>', true)
    .addField("addrole", 'lxaddrole <user> <role>', true)
    .addField("announce", `lxannounce <channel> <text>`, true)
    .addField("delrole", 'lxdelrole <user> <role>', true)


    let embed2 = new Discord.MessageEmbed()
    .setColor("GOLD")
    .addField("unmute", 'lxunmute <user>', true)
    .addField("tempmute", 'lxtempmute <user> <time> [reason]', true)
    .addField("purge", 'lxpurge <amount>', true)
    .addField("purgeuser", `lxpurgeuser <user>`, true)
    .addField("setnick", `lxsetnick <user> <name>`, true)
    .addField("resetnick", `lxresetnick <user>`, true)
    .addField("slowmode", `lxslowmode <time>`, true)
    .addField("warn", 'lxwarn <user> <reason>', true)
    .addField("warning", `lxwarning <user>`, true)
    .addField("resetwarn", `lxresetwarn <user>`, true)
    .addField("dm", 'lxdm <user> <text>', true)
    .addField("lock", 'lxlock', true)
    .addField("lockdown", 'lxlockdown ', true)
    .addField("mute", 'lxmute <user> [reason]', true)
    .addField("bugreport", 'lxbugreport <text>', true)
    .addField("addpoint", 'lxaddpoint <user> <nominal>', true)
    .addField("resetpoint", 'lxresetpoint <user>', true)
    .addField("points", 'lxpoints [user]', true)
    .setTimestamp()
    .setFooter('<> = Required | [] = Optional | Time = 5s (seconds)/ 5m (minutes)/ 5h (hours)')
    message.channel.send(embed).then(async (message) => {
      message.channel.send(embed2)
    });
}